accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('sign-up/info-account-activation/', views.info_account_activation, name='info_account_activation'),
    path('sign-up/confermation-account/<slug:uidb64>/<slug:token>/', views.activate_account, name='activate_account'),
    path('dashboard/accounts/update/profile/', views.update_profile, name='update_profile'),
    path('dashboard/accounts/delete/account/', views.delete_user, name="delete_user"),
    path('dashboard/ads/', views.user_ads, name="user_ads"),
    path('dashboard/wishlist/', views.user_wishlist, name="user_wishlist"),
    path('dashboard/reviews/', views.user_reviews, name="user_reviews"),
    path('dashboard/update/review/<uuid:review_id>/', views.update_review, name="update_review"),
    path('dashboard/delete/review/<uuid:review_id>/', views.delete_review, name="delete_review"),
    path('profile/<str:unique_code>/', views.public_profile, name="public_profile"),
]

ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('announcements/', views.announcements,
         name="announcements"),
    path('announcements/<slug:category_slug>/', views.categories_and_sub,
         name="announcements_by_category"),
    path('announcements/<slug:category_slug>/<slug:sabcategory_slug>/', views.categories_and_sub,
         name="announcements_by_subcategory"),
    path('announcements/add/to/wishlist/', views.ann_wishlist,
         name="ann_wishlist"),
    path('announcements/add/to/wishlist/<uuid:announcement_id>/', views.ann_wishlist,
         name="ann_wishlist_detail"),
    path('announcement/<slug:slug>/detail/', views.announcement_detail,
         name="announcement_detail"),
    path('add/announcement/<uuid:category_id>/<uuid:subcat_id>/', views.add_standard_announcement,
         name="add_standard_announcement"),
    path('update/announcement/<uuid:ann_id>/', views.update_standard_announcement,
         name="update_standard_announcement"),
    path('delete/announcement/<uuid:ann_id>/', views.delete_announcement,
         name="delete_announcement"),
    path('change-status/announcement/<uuid:ann_id>/', views.change_status_announcement,
         name="change_status_announcement"),
    path('add/images/announcement/<uuid:ad_id>/', views.add_image_announcement,
         name="add_image_announcement"),
    path('modify/images/announcement/<uuid:image_id>/', views.modify_image_announcement,
         name="modify_image_announcement"),
    path('delete/images/announcement/<uuid:image_id>/', views.delete_image_announcement,
         name="delete_image_announcement"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.forms import EmailValidationOnForgotPassword
from .sitemaps import StaticViewSitemap, AnnouncementSitemap, CategorySitemap, SubCategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
    'announcement_ad': AnnouncementSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ads.urls', namespace='ads')),
    path('', include('engines.urls', namespace='engines')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('jobs.urls', namespace='jobs')),
    path('', include('property.urls', namespace='property')),
    path('', include('reviews.urls', namespace='reviews')),
    path('', include('chat.urls', namespace='chat')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.home, name='home'),
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('cookie/', views.cookie, name='cookie'),
]

accounts/models.py
import random
import string
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator, validate_image_file_extension, validate_ipv46_address
from django.db import models
from django.db.models import Count, Avg, Q
from django.utils.translation import gettext_lazy as _

from cities.models import Cities
from .utils import validate_file_size, user_directory_path


# Create your models here.
class User(AbstractUser):
    class UserTypeChoice(models.TextChoices):
        COMPANY = 'CO', _('Company')
        INDIVIDUAL = 'PE', _('Individual Person')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    u_type = models.CharField(max_length=20, choices=UserTypeChoice.choices)
    email_confirmation = models.BooleanField(default=False)
    terms_and_privacy = models.BooleanField()
    ip = models.GenericIPAddressField(validators=[validate_ipv46_address])


def generate_unique_code():
    unique_code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
    try:
        Profile.objects.get(unique_code=unique_code)
        return generate_unique_code()
    except Profile.DoesNotExist:
        return unique_code


class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name="user_profile_related",
                                related_query_name="user_profile", )
    city = models.ForeignKey(Cities, on_delete=models.CASCADE, related_name="user_city", blank=True, null=True)
    avatar = models.ImageField(upload_to=user_directory_path, validators=[
        validate_image_file_extension, FileExtensionValidator(['JPEG', 'JPG', 'PNG']), validate_file_size,
    ], blank=True, null=True)
    unique_code = models.CharField(max_length=8, default=generate_unique_code, unique=True)
    phone = models.CharField(max_length=9, blank=True, null=True)
    hidden_phone = models.BooleanField(default=False)
    is_complete = models.BooleanField(default=False)
    age = models.PositiveSmallIntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def count_ad_by_status(self):
        return self.announcement_user_profile.aggregate(
            published=Count('id', filter=Q(status="AP")),
            waiting=Count('id', filter=Q(status="WA")),
            reject=Count('id', filter=Q(status="RE")),
        )

    def get_reviews_avg(self):
        return self.review_profile.select_related('profile', 'user').filter(status="AP").aggregate(
            review_number=Count('id'), review_avg=Avg('rating')
        )

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.unique_code:
            self.unique_code = generate_unique_code()
        super().save(*args, **kwargs)


class Individual(Profile):
    class GenderChoices(models.TextChoices):
        empty = "", "Select gender"
        MALE = 'ML', _('Male')
        FEMALE = 'FM', _('Female')
        OTHER = 'OTH', _('Other')
        PREFER_NOT_TO_SAY = 'PS', _('Prefer Not To Say')

    gender = models.CharField(max_length=3, choices=GenderChoices.choices, default=GenderChoices.PREFER_NOT_TO_SAY)

    def __str__(self):
        return f"Profile of {self.user.username}"

    class Meta:
        verbose_name = "Individual Person"
        verbose_name_plural = "Individual Persons"


class Company(Profile):
    name = models.CharField(max_length=200)
    vat_number = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=4)

    def __str__(self):
        return f"Profile {self.user.username} - {self.name}"

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.sites.shortcuts import get_current_site
from django.forms import Select, TextInput, NumberInput, RadioSelect, CheckboxInput
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from .models import User, Individual, Company, Profile
from .token import token_generator


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control form-control-lg mb-2', 'placeholder': 'Username'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control form-control-lg mb-2', 'placeholder': 'Password'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control form-control-lg mb-2', 'placeholder': 'Password confirmation'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control form-control-lg', 'placeholder': 'Enter your email'
        })
        self.fields['terms_and_privacy'].widget.attrs.update({'class': 'form-check-input'})

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'u_type', 'terms_and_privacy']
        widgets = {
            'u_type': RadioSelect({'class': 'list-group-item-check pe-none'}),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('That username is already taken.')
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password_mismatch.')
        return password2

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('This email address is already registered.')
        return email

    def send_activation_email(self, request, user):
        current_site = get_current_site(request)
        subject = 'Activate Your Account'
        message = render_to_string(
            'accounts/email_activation.html',
            {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token_generator.make_token(user),
            }
        )

        user.email_user(subject, message, html_message=message)


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no guest registered with the specified email address!")
        return email


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control form-control-lg', 'placeholder': 'First Name', 'required': 'required'
            }),
            'last_name': TextInput(attrs={
                'class': 'form-control form-control-lg', 'placeholder': 'Last Name', 'required': 'required'
            }),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not all(first_name.isalpha() or first_name.isspace() for first_name in first_name):
            raise forms.ValidationError('This field can only contain letters.')
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if not all(last_name.isalpha() or last_name.isspace() for last_name in last_name):
            raise forms.ValidationError('This field can only contain letters.')
        return last_name


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs.update({
            'class': 'form-control form-control-lg', 'accept': '.jpg, .jpeg, .png'
        })

    class Meta:
        model = Profile
        fields = ('city', 'avatar', 'phone', 'hidden_phone', 'age')

        widgets = {
            'city': Select(attrs={'class': 'form-select form-select-lg select-field', 'placeholder': 'City'}),
            'phone': TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Phone Number'}),
            'hidden_phone': CheckboxInput(attrs={'class': 'form-check-input'}),
            'age': NumberInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Age'}),
        }

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        if not all(phone.isnumeric() for phone in phone):
            raise forms.ValidationError("This field accepts only numbers.")
        return phone

    def clean_age(self):
        age = self.cleaned_data.get("age")
        if age < 18:
            raise forms.ValidationError("You must be at least 18 years old to register.")
        else:
            if age > 99:
                raise forms.ValidationError("Check that you have entered your age correctly.")
        return age


class IndividualProfileForm(UserProfileForm):
    class Meta:
        model = Individual
        fields = UserProfileForm.Meta.fields + ('gender',)

        widgets = {
            **UserProfileForm.Meta.widgets,
            'gender': Select(attrs={'class': 'form-select form-select-lg select-field', 'placeholder': 'Gender'}),
        }


class CompanyProfileForm(UserProfileForm):
    class Meta:
        model = Company
        fields = ('name', 'vat_number', 'address', 'zip_code') + UserProfileForm.Meta.fields

        widgets = {
            **UserProfileForm.Meta.widgets,
            'name': TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Company Name'}),
            'vat_number': TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Vat Number'}),
            'address': TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Address'}),
            'zip_code': NumberInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Zip Code'}),
        }

        labels = {
            'name': 'Company Name',
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        if Company.objects.filter(name__iexact=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('That company name is already taken.')
        return name

    def clean_vat_number(self):
        vat_number = self.cleaned_data['vat_number']
        if Company.objects.filter(vat_number__iexact=vat_number).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('That Vat Number name is already taken.')
        return vat_number

    def clean_address(self):
        address = self.cleaned_data['address']
        if not all(address.isalnum() or address.isspace() or address in [',', '.', '-', "'", '(', ')', '"']
                   for address in address):
            raise forms.ValidationError(
                'This field can only contain letters, numbers and ,.-"()')
        return address

templates/accounts/email_activation.html
{% autoescape off %}
    Hello nice to meet you {{ user.first_name }},

    Click on the following link to confirm your registration:

    http://{{ domain }}{% url 'accounts:activate_account' uidb64=uid token=token %}

    A greeting,
    The Staff of Kalipso
{% endautoescape %}

templates/accounts/email_activation_invalid.html
{% extends 'base.html' %}
{% block title %}link invalid{% endblock %}
{% block description %}link invalid{% endblock %}
{% block keywords %}link invalid{% endblock %}
{% block ogtitle %}link invalid{% endblock %}
{% block ogdescription %}link invalid{% endblock %}
{% block content %}
    <section class="msg-activation-fail py-65">
        <div class="row">
            <div class="card card-background w-50 mx-auto">
                <div class="card-body p-5 text-center">
                    <h5>
                        The confirmation link is invalid, probably because it has already been used.
                    </h5>
                    <div>
                        <i class="bi bi-emoji-frown display-1"></i>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/message_activation_account.html
{% extends 'base.html' %}
{% block title %}active account{% endblock %}
{% block description %}active account{% endblock %}
{% block keywords %}active account{% endblock %}
{% block ogtitle %}active account{% endblock %}
{% block ogdescription %}active account{% endblock %}
{% block content %}
    <section class="msg-activation py-65">
        <div class="row">
            <div class="col-md-8 col-lg-6 mx-auto">
                <div class="card card-background text-center">
                    <div class="card-body">
                        <div>
                            <i class="bi bi-envelope-check display-1"></i>
                        </div>
                        <p>
                            To complete the creation of your account, you must click on the link in the email we sent
                            you.
                            If you don't receive the email in your inbox, it's possible that has been marked as spam.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/sign-up.html
{% extends 'base.html' %}
{% load static %}
{% block title %}sign_up{% endblock %}
{% block description %}sign_up{% endblock %}
{% block keywords %}sign_up{% endblock %}
{% block ogtitle %}sign_up{% endblock %}
{% block ogdescription %}sign_up{% endblock %}
{% block content %}
    <div class="row g-lg-5 justify-content-center">
        <div class="col-12">
            <div class="card card-background-sign">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-md-6 d-none d-md-block d-lg-block d-xl-block d-xxl-block">
                            <div class="d-flex flex-column mb-3 border-right-end align-items-center text-white border-color-cs">
                                <div class="p-2">
                                    <h1 class="h3">Join Classafield.</h1>
                                    <h2 class="h3">Get premium benefits:</h2>
                                    <ul class="list-unstyled text-start">
                                        <li>
                                            <i class="bi bi-check-circle-fill"></i> Add and promote your listings
                                        </li>
                                        <li>
                                            <i class="bi bi-check-circle-fill"></i> Easily manage your wishlist
                                        </li>
                                        <li>
                                            <i class="bi bi-check-circle-fill"></i> Leave reviews
                                        </li>
                                    </ul>
                                </div>
                                <div class="p-2">
                                    <img src="{% static 'img/sign-up.svg' %}" alt="" height="292"
                                         class="mx-auto w-100">
                                </div>
                                <div class="p-2">Already have an account?
                                    <a href="{% url 'login' %}" class="text-white">Sign in</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 text-white">
                            <h2>Register</h2>
                            <p>Create your account to start selling and buying.</p>
                            <!-- Form -->
                            <form method="post" action="{% url 'accounts:sign_up' %}" autocomplete="off">
                                {% csrf_token %}
                                <div class="mb-3">
                                    {{ form.username }}
                                    <span class="ms-2">{{ form.username.help_text }}</span>
                                    <span class="text-danger">{{ form.username.errors }}</span>
                                </div>
                                <div class="mb-3">
                                    {{ form.email }}
                                    <span class="text-danger">{{ form.email.errors }}</span>
                                </div>
                                <div class="mb-3">
                                    {{ form.password1 }}
                                    {{ form.password1.help_text }}
                                </div>
                                <div class="mb-3">
                                    {{ form.password2 }}
                                    <span class="ms-2">{{ form.password2.help_text }}</span>
                                    <span class="text-danger">{{ form.password2.errors }}</span>
                                </div>
                                <div class="mb-3">
                                    <div class="list-group list-group-checkable border-0 w-auto list-group-horizontal justify-content-between gap-3">
                                        {% for radio in form.u_type %}
                                            {% if forloop.counter0 > 0 %}
                                                {{ radio.tag }}
                                                <label class="list-group-item rounded-3 p-3 w-50 card-background"
                                                       for="{{ radio.id_for_label }}">
                                                    {{ radio.choice_label }}
                                                    <span class="d-block small">
                                                        {% if radio.choice_label == "Individual Person" %}
                                                            I am a Individual Person
                                                        {% else %}
                                                            After sign up you can set up your business profile
                                                        {% endif %}
                                                    </span>
                                                </label>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <div class="form-check">
                                        {{ form.terms_and_privacy }}
                                        <label class="form-check-label" for="id_terms_and_privacy">
                                            I agree to the
                                            <span>
                                                <a href="{% url 'pages:terms' %}" class="text-primary">
                                                    Terms of Service
                                                </a>and
                                                <a href="{% url 'pages:privacy' %}" class="text-primary">Privacy Policy.
                                                </a>
                                            </span>
                                        </label>
                                        {{ form.terms_and_privacy.errors }}
                                    </div>
                                </div>
                                <!-- Button -->
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary">
                                        Create Free Account
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}