ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('announcements/', views.announcements,
         name="announcements"),
    path('announcements/<slug:category_slug>/', views.categories_and_sub,
         name="announcements_by_category"),
    path('announcements/<slug:category_slug>/<slug:sabcategory_slug>/', views.categories_and_sub,
         name="announcements_by_subcategory"),
    path('announcements/add/to/wishlist/', views.ann_wishlist,
         name="ann_wishlist"),
    path('announcements/add/to/wishlist/<uuid:announcement_id>/', views.ann_wishlist,
         name="ann_wishlist_detail"),
    path('announcement/<slug:slug>/detail/', views.announcement_detail,
         name="announcement_detail"),
    path('add/announcement/<uuid:category_id>/<uuid:subcat_id>/', views.add_standard_announcement,
         name="add_standard_announcement"),
    path('update/announcement/<uuid:ann_id>/', views.update_standard_announcement,
         name="update_standard_announcement"),
    path('delete/announcement/<uuid:ann_id>/', views.delete_announcement,
         name="delete_announcement"),
    path('change-status/announcement/<uuid:ann_id>/', views.change_status_announcement,
         name="change_status_announcement"),
    path('add/images/announcement/<uuid:ad_id>/', views.add_image_announcement,
         name="add_image_announcement"),
    path('modify/images/announcement/<uuid:image_id>/', views.modify_image_announcement,
         name="modify_image_announcement"),
    path('delete/images/announcement/<uuid:image_id>/', views.delete_image_announcement,
         name="delete_image_announcement"),
]

categories/urls.py
from django.urls import path
from . import views

app_name = "categories"

urlpatterns = [
    path('choose-the-category/', views.categories_list, name="categories_list"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.forms import EmailValidationOnForgotPassword
from .sitemaps import StaticViewSitemap, AnnouncementSitemap, CategorySitemap, SubCategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
    'announcement_ad': AnnouncementSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ads.urls', namespace='ads')),
    path('', include('engines.urls', namespace='engines')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('jobs.urls', namespace='jobs')),
    path('', include('property.urls', namespace='property')),
    path('', include('reviews.urls', namespace='reviews')),
    path('', include('chat.urls', namespace='chat')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

engines/urls.py
from django.urls import path
from . import views

app_name = "engines"

urlpatterns = [
    path('add/announcement/auto/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_auto,
         name="add_announcement_auto"),
    path('update/announcement/auto/<uuid:ann_id>/', views.update_announcement_auto,
         name="update_announcement_auto"),
    path('add/announcement/moto/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_moto,
         name="add_announcement_moto"),
    path('update/announcement/moto/<uuid:ann_id>/', views.update_announcement_moto,
         name="update_announcement_moto"),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('add/announcement/job/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_job,
         name="add_announcement_job"),
    path('update/announcement/job/<uuid:ann_id>/', views.update_announcement_job,
         name="update_announcement_job"),
]

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path('add/announcement/property/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_property,
         name="add_announcement_property"),
    path('update/announcement/property/<uuid:ann_id>/', views.update_announcement_property,
         name="update_announcement_property"),
    path('add/announcement/property/aparments/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_apartments,
         name="add_announcement_apartments"),
    path('update/announcement/property/aparments/<uuid:ann_id>/', views.update_announcement_apartments,
         name="update_announcement_apartments")
]

categories/models.py
import uuid

from django.conf import settings
from django.core.validators import validate_slug
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from .queryset import CategoryQuerySet


class ManageForms(models.Model):
    active_form_standard = models.BooleanField(default=False)
    active_form_auto = models.BooleanField(default=False)
    active_form_moto = models.BooleanField(default=False)
    active_form_jobs = models.BooleanField(default=False)
    active_form_properties = models.BooleanField(default=False)
    active_form_apartments = models.BooleanField(default=False)

    class Meta:
        abstract = True


class ManageFilters(models.Model):
    filter_condition = models.BooleanField(default=False)
    filter_transmissions = models.BooleanField(default=False)
    filter_fuels = models.BooleanField(default=False)
    filter_ad_types = models.BooleanField(default=False)
    filter_schedules = models.BooleanField(default=False)
    filter_levels = models.BooleanField(default=False)
    filter_price_min = models.BooleanField(default=False)
    filter_price_max = models.BooleanField(default=False)

    class Meta:
        abstract = True


# Create your models here.
class Category(ManageFilters):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_category')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True, validators=[validate_slug])
    is_active = models.BooleanField(default=False)
    icon = models.CharField(max_length=50)
    bg_class_name = models.CharField(max_length=50, default="bg-yellow")
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()  # The default manager.
    category_manager = CategoryQuerySet.as_manager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def clean(self):
        if SubCategory.objects.filter(slug=self.slug).exists():
            raise ValidationError(
                'This slug already exists in the subcategory, it must be unique between the category and subcategory.'
            )

    def get_absolute_url(self):
        return reverse('ads:announcements_by_category', args=[self.slug])


class SubCategory(ManageFilters, ManageForms):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_subategory')
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, related_name='category_in_sub')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True, validators=[validate_slug])
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Sub Category'
        verbose_name_plural = 'Sub Categories'

    def __str__(self):
        return self.name

    def clean(self):
        if Category.objects.filter(slug=self.slug).exists():
            raise ValidationError(
                'This slug already exists in the category, it must be unique between the category and subcategory.'
            )

    def get_absolute_url(self):
        return reverse('ads:announcements_by_subcategory', args=[self.category.slug, self.slug])

categories/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Category

@login_required
def categories_list(request):
    categories = Category.category_manager.active_categories()
    context = {
        'categories': categories,
    }
    return render(request, 'categories/list.html', context)

templates/categories/ann_by_cat_and_sub.html
{% extends 'base.html' %}
{% load static %}
{% load query_helpers %}
{% load detects_mobile %}
{% block content %}
    <section class="obj-{% if subcategory %}categories{% else %}-subcategories{% endif %}">
        <div class="row">
            {% include 'ads/partial/filters/search_form.html' %}
            {% if not request|is_mobile %}
                <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-3 d-none d-sm-none d-md-block">
                    {% if subcategory.filter_condition or category.filter_condition %}
                        {% include 'ads/partial/filters/conditions.html' %}
                    {% endif %}
                    {% if subcategory.filter_ad_types or category.filter_ad_types %}
                        {% include 'ads/partial/filters/ad_types.html' %}
                    {% endif %}
                    {% if subcategory.filter_fuels or category.filter_fuels %}
                        {% include 'ads/partial/filters/fuels.html' %}
                    {% endif %}
                    {% if subcategory.filter_transmissions or category.filter_transmissions %}
                        {% include 'ads/partial/filters/transmissions.html' %}
                    {% endif %}
                    {% if subcategory.filter_price_min and subcategory.filter_price_max or category.filter_price_min and category.filter_price_max %}
                        {% include 'ads/partial/filters/price_filter.html' %}
                    {% endif %}
                    {% if subcategory.filter_schedules or category.filter_schedules %}
                        {% include 'ads/partial/filters/schedules.html' %}
                    {% endif %}
                    {% if subcategory.filter_levels or category.filter_levels %}
                        {% include 'ads/partial/filters/levels.html' %}
                    {% endif %}
                </div>
            {% endif %}
            <div class="col-xxl-10 col-xl-10 col-lg-10 col-md-9 col-sm-12 col-12">
                <div class="d-flex flex-row mb-3 align-items-center">
                    {% if request|is_mobile %}
                        <div class="p-1 d-block d-sm-block d-md-none">
                            {% include 'ads/partial/filters/mobile_filter.html' %}
                        </div>
                    {% endif %}
                    <div class="p-1 text-white">
                        <i class="bi bi-arrow-down-up"></i> Sort By:
                    </div>
                    <div class="p-1">
                        {% include 'ads/partial/filters/sorting.html' %}
                    </div>
                    <div class="p-1 ms-auto text-white">
                        {{ announcements|length }} offers
                    </div>
                </div>
                {% for ads in announcements %}
                    {% include 'ads/partial/card.html' %}
                {% empty %}
                    {% include 'partial/no_result_found.html' %}
                {% endfor %}
                {% include 'partial/pagination.html' with page_obj=announcements %}
            </div>
        </div>
    </section>
{% endblock %}

templates/categories/list.html
{% extends 'base.html' %}
{% block title %}Cookies{% endblock %}
{% block description %}Cookies{% endblock %}
{% block keywords %}Cookies{% endblock %}
{% block ogtitle %}Cookies{% endblock %}
{% block ogdescription %}Cookies{% endblock %}
{% block content %}
    <div class="row text-white">
        <h2>Place your ad in minutes</h2>
        <p class="mb-5">Sell online what you no longer use and start earning</p>
        {% for category in categories %}
            <div class="col-md-6 col-lg-3">
                <div class="card border-0 {{ category.bg_class_name }} mb-5">
                    <div class="card-header border-0 text-uppercase text-white fw-bold">
                        <div class="d-flex flex-row justify-content-center align-items-center">
                            <div class="p-1">
                                <i class="{{ category.icon }} fs-2"></i>
                            </div>
                            <div class="p-2 fs-4" style="letter-spacing: 2px;">{{ category.name|capfirst }}</div>
                        </div>
                    </div>
                    <div class="card-body mx-auto">
                        <div class="dropdown dropdown-center">
                            <button class="btn btn-white border-0" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-patch-plus-fill display-6 text-white"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                {% for sub in category.category_in_sub.all %}
                                    <li>
                                        {% if sub.active_form_auto %}
                                            <a class="dropdown-item"
                                               href="{% url 'engines:add_announcement_auto' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% elif sub.active_form_moto %}
                                            <a class="dropdown-item"
                                               href="{% url 'engines:add_announcement_moto' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% elif sub.active_form_jobs %}
                                            <a class="dropdown-item"
                                               href="{% url 'jobs:add_announcement_job' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% elif sub.active_form_apartments %}
                                            <a class="dropdown-item"
                                               href="{% url 'property:add_announcement_apartments' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% elif sub.active_form_properties %}
                                            <a class="dropdown-item"
                                               href="{% url 'property:add_announcement_property' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% elif sub.active_form_standard %}
                                            <a class="dropdown-item"
                                               href="{% url 'ads:add_standard_announcement' sub.category.id sub.id %}">{{ sub.name }}</a>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}