accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('sign-up/info-account-activation/', views.info_account_activation, name='info_account_activation'),
    path('sign-up/confermation-account/<slug:uidb64>/<slug:token>/', views.activate_account, name='activate_account'),
    path('dashboard/accounts/update/profile/', views.update_profile, name='update_profile'),
    path('dashboard/accounts/delete/account/', views.delete_user, name="delete_user"),
    path('dashboard/ads/', views.user_ads, name="user_ads"),
    path('dashboard/wishlist/', views.user_wishlist, name="user_wishlist"),
    path('dashboard/reviews/', views.user_reviews, name="user_reviews"),
    path('dashboard/update/review/<uuid:review_id>/', views.update_review, name="update_review"),
    path('dashboard/delete/review/<uuid:review_id>/', views.delete_review, name="delete_review"),
    path('profile/<str:unique_code>/', views.public_profile, name="public_profile"),
]

ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('announcements/', views.announcements,
         name="announcements"),
    path('announcements/<slug:category_slug>/', views.categories_and_sub,
         name="announcements_by_category"),
    path('announcements/<slug:category_slug>/<slug:sabcategory_slug>/', views.categories_and_sub,
         name="announcements_by_subcategory"),
    path('announcements/add/to/wishlist/', views.ann_wishlist,
         name="ann_wishlist"),
    path('announcements/add/to/wishlist/<uuid:announcement_id>/', views.ann_wishlist,
         name="ann_wishlist_detail"),
    path('announcement/<slug:slug>/detail/', views.announcement_detail,
         name="announcement_detail"),
    path('add/announcement/<uuid:category_id>/<uuid:subcat_id>/', views.add_standard_announcement,
         name="add_standard_announcement"),
    path('update/announcement/<uuid:ann_id>/', views.update_standard_announcement,
         name="update_standard_announcement"),
    path('delete/announcement/<uuid:ann_id>/', views.delete_announcement,
         name="delete_announcement"),
    path('change-status/announcement/<uuid:ann_id>/', views.change_status_announcement,
         name="change_status_announcement"),
    path('add/images/announcement/<uuid:ad_id>/', views.add_image_announcement,
         name="add_image_announcement"),
    path('modify/images/announcement/<uuid:image_id>/', views.modify_image_announcement,
         name="modify_image_announcement"),
    path('delete/images/announcement/<uuid:image_id>/', views.delete_image_announcement,
         name="delete_image_announcement"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.forms import EmailValidationOnForgotPassword
from .sitemaps import StaticViewSitemap, AnnouncementSitemap, CategorySitemap, SubCategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
    'announcement_ad': AnnouncementSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ads.urls', namespace='ads')),
    path('', include('engines.urls', namespace='engines')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('jobs.urls', namespace='jobs')),
    path('', include('property.urls', namespace='property')),
    path('', include('reviews.urls', namespace='reviews')),
    path('', include('chat.urls', namespace='chat')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

engines/urls.py
from django.urls import path
from . import views

app_name = "engines"

urlpatterns = [
    path('add/announcement/auto/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_auto,
         name="add_announcement_auto"),
    path('update/announcement/auto/<uuid:ann_id>/', views.update_announcement_auto,
         name="update_announcement_auto"),
    path('add/announcement/moto/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_moto,
         name="add_announcement_moto"),
    path('update/announcement/moto/<uuid:ann_id>/', views.update_announcement_moto,
         name="update_announcement_moto"),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = "jobs"

urlpatterns = [
    path('add/announcement/job/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_job,
         name="add_announcement_job"),
    path('update/announcement/job/<uuid:ann_id>/', views.update_announcement_job,
         name="update_announcement_job"),
]

property/urls.py
from django.urls import path
from . import views

app_name = "property"

urlpatterns = [
    path('add/announcement/property/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_property,
         name="add_announcement_property"),
    path('update/announcement/property/<uuid:ann_id>/', views.update_announcement_property,
         name="update_announcement_property"),
    path('add/announcement/property/aparments/<uuid:category_id>/<uuid:subcat_id>/', views.add_announcement_apartments,
         name="add_announcement_apartments"),
    path('update/announcement/property/aparments/<uuid:ann_id>/', views.update_announcement_apartments,
         name="update_announcement_apartments")
]

templates/accounts/dashboard/partial/dropdown.html
<div class="dropdown">
    <button class="btn btn-dark dropdown-toggle dropdown-three-dots" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-three-dots-vertical"></i>
    </button>
    <ul class="dropdown-menu dropdown-menu-dark">
        <li>
            <a class="dropdown-item"
                    {% if ads.standard.auto %}
               href="{% url 'engines:update_announcement_auto' ads.id %}"
                    {% elif ads.standard.moto %}
               href="{% url 'engines:update_announcement_moto' ads.id %}"
                    {% elif ads.jobs %}
               href="{% url 'jobs:update_announcement_job' ads.id %}"
                    {% elif ads.properties.house %}
               href="{% url 'property:update_announcement_apartments' ads.id %}"
                    {% elif ads.properties and not ads.properties.house %}
               href="{% url 'property:update_announcement_property' ads.id %}"
                    {% else %}
               href="{% url 'ads:update_standard_announcement' ads.id %}"
                    {% endif %}> <i class="bi bi-pencil-square"></i> Edit
            </a>
        </li>
        <li>
            <!-- Button trigger modal -->
            <button type="button" class="btn bdropdown-item color-text-dropdown" data-bs-toggle="modal"
                    data-bs-target="#exampleModal-{{ ads.id }}">
                <i class="bi bi-power"></i> Deactive
            </button>
        </li>
        <li>
            <!-- Button trigger modal -->
            <button type="button" class="btn bdropdown-item color-text-dropdown" data-bs-toggle="modal"
                    data-bs-target="#exampleModal-{{ ads.slug }}">
                <i class="bi bi-trash3"></i> Delete
            </button>
        </li>
    </ul>
</div>
{% url 'ads:change_status_announcement' ads.id as change_status %}
{% with title='Are you sure you want to make this change?' description='If you change your mind, you can change the status of your ad again.' %}
    {% include 'partial/modal.html' with modal_id=ads.id title=title description=description action_url=change_status %}
{% endwith %}
{% url 'ads:delete_announcement' ads.id as delete_ads %}
{% with title='Are you sure you want to delete this ad?' description='A deleted advertisement can no longer be recovered.' %}
    {% include 'partial/modal.html' with modal_id=ads.slug title=title description=description action_url=delete_ads %}
{% endwith %}

templates/accounts/dashboard/partial/sidebar_tab.html
{% load static %}
<div class="list-group">
    <div class="card card-background">
        <div class="card-body">
            <p class="card-text">{{ request.user.get_u_type_display }} </p>
            <div class="d-flex">
                <div class="flex-shrink-0">
                    <img src="{% if request.user.user_profile_related.company.avatar %}{{ request.user.user_profile_related.company.avatar.url }}{% elif request.user.user_profile_related.individual.avatar %}{{ request.user.user_profile_related.individual.avatar.url }}{% else %}{% static 'img/male_avatar.svg' %}{% endif %}"
                         class="rounded-4" alt="..." height="50" width="50">
                </div>
                <div class="flex-grow-1 ms-2">
                    <h5 class="mb-0">{{ request.user.get_full_name }}</h5>
                    <ul class="list-unstyled">
                        {% include 'reviews/partial/review_rating.html' with rating=request.user.user_profile_related.get_reviews_avg.review_avg %}
                        <li class="list-inline-item small">
                            ({{ request.user.user_profile_related.get_reviews_avg.review_number }}
                            review{{ request.user.user_profile_related.get_reviews_avg.review_number|pluralize }})
                        </li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>
                            <i class="bi bi-phone"></i> +355 {{ request.user.user_profile_related.phone }}
                            <i class="bi bi-eye"></i> {{ request.user.user_profile_related.hidden_phone }}
                        </li>
                        <li>
                            <i class="bi bi-envelope"></i> {{ request.user.email }}
                        </li>
                    </ul>
                </div>
            </div>
            <a href="{% url 'categories:categories_list' %}" class="btn btn-primary btn-orange btn-lg fw-bold w-100">
                <i class="bi bi-plus"></i> Ad ad
            </a>
        </div>
    </div>
    <a href="{% url 'accounts:update_profile' %}"
       class="list-group-item list-group-item-action border-end-0 p-3 card-background {% if section == "profile" %}border-left-active{% endif %}"
       aria-current="true">
        <i class="bi bi-person fs-5"></i> Personal Info
    </a>
    <a href="{% url 'password_change' %}"
       class="list-group-item list-group-item-action border-end-0 p-3 card-background {% if request.path == "/accounts/password_change/" %}border-left-active{% endif %}">
        <i class="bi bi-lock"></i> Password e security
    </a>
    <a href="{% url 'accounts:user_ads' %}"
       class="list-group-item list-group-item-action border-end-0 p-3 card-background {% if section == "user_ads" %}border-left-active{% endif %}">
        <i class="bi bi-list-ul"></i> My ads
    </a>
    <a href="{% url 'accounts:user_wishlist' %}"
       class="list-group-item list-group-item-action border-end-0 p-3 card-background {% if section == "user_wish" %}border-left-active{% endif %}">
        <i class="bi bi-suit-heart"></i> Wish list
    </a>
    <a href="{% url 'accounts:user_reviews' %}"
       class="list-group-item list-group-item-action border-end-0 p-3 card-background {% if section == "user_review" %}border-left-active{% endif %}">
        <i class="bi bi-star"></i> Reviews
    </a>
    <a href="{% url 'logout' %}" class="list-group-item list-group-item-action border-end-0 p-3 card-background">
        <i class="bi bi-box-arrow-right"></i> Sign out
    </a>
</div>