accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('sign-up/info-account-activation/', views.info_account_activation, name='info_account_activation'),
    path('sign-up/confermation-account/<slug:uidb64>/<slug:token>/', views.activate_account, name='activate_account'),
    path('dashboard/accounts/update/profile/', views.update_profile, name='update_profile'),
    path('dashboard/accounts/delete/account/', views.delete_user, name="delete_user"),
    path('dashboard/ads/', views.user_ads, name="user_ads"),
    path('dashboard/wishlist/', views.user_wishlist, name="user_wishlist"),
    path('dashboard/reviews/', views.user_reviews, name="user_reviews"),
    path('dashboard/update/review/<uuid:review_id>/', views.update_review, name="update_review"),
    path('dashboard/delete/review/<uuid:review_id>/', views.delete_review, name="delete_review"),
    path('profile/<str:unique_code>/', views.public_profile, name="public_profile"),
]

ads/urls.py
from django.urls import path
from . import views

app_name = "ads"

urlpatterns = [
    path('announcements/', views.announcements,
         name="announcements"),
    path('announcements/<slug:category_slug>/', views.categories_and_sub,
         name="announcements_by_category"),
    path('announcements/<slug:category_slug>/<slug:sabcategory_slug>/', views.categories_and_sub,
         name="announcements_by_subcategory"),
    path('announcements/add/to/wishlist/', views.ann_wishlist,
         name="ann_wishlist"),
    path('announcements/add/to/wishlist/<uuid:announcement_id>/', views.ann_wishlist,
         name="ann_wishlist_detail"),
    path('announcement/<slug:slug>/detail/', views.announcement_detail,
         name="announcement_detail"),
    path('add/announcement/<uuid:category_id>/<uuid:subcat_id>/', views.add_standard_announcement,
         name="add_standard_announcement"),
    path('update/announcement/<uuid:ann_id>/', views.update_standard_announcement,
         name="update_standard_announcement"),
    path('delete/announcement/<uuid:ann_id>/', views.delete_announcement,
         name="delete_announcement"),
    path('change-status/announcement/<uuid:ann_id>/', views.change_status_announcement,
         name="change_status_announcement"),
    path('add/images/announcement/<uuid:ad_id>/', views.add_image_announcement,
         name="add_image_announcement"),
    path('modify/images/announcement/<uuid:image_id>/', views.modify_image_announcement,
         name="modify_image_announcement"),
    path('delete/images/announcement/<uuid:image_id>/', views.delete_image_announcement,
         name="delete_image_announcement"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from accounts.forms import EmailValidationOnForgotPassword
from .sitemaps import StaticViewSitemap, AnnouncementSitemap, CategorySitemap, SubCategorySitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticViewSitemap,
    'announcement_ad': AnnouncementSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('ads.urls', namespace='ads')),
    path('', include('engines.urls', namespace='engines')),
    path('', include('categories.urls', namespace='categories')),
    path('', include('jobs.urls', namespace='jobs')),
    path('', include('property.urls', namespace='property')),
    path('', include('reviews.urls', namespace='reviews')),
    path('', include('chat.urls', namespace='chat')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt', include('robots.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

ads/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect

from accounts.decorators import profile_complete_required
from categories.models import Category, SubCategory
from chat.forms import MessageForm
from .forms import SearchForm, StandardAdsForm, ImageForm, UpdateStandardAdsForm
from .models import Announcement, Image, Standard


# Create your views here.
#
def is_valid_queryparam(param):
    return param != '' and param is not None


def announcements(request):
    subcategory = None
    category_f = None
    objects_list = Announcement.ad_manager.active_ad()
    form = SearchForm(request.GET)
    if form.is_valid():
        keyword_q = form.cleaned_data['keyword_q']
        category = form.cleaned_data['categories']
        city = form.cleaned_data['cities']
        condition = form.cleaned_data['condition']
        sorting = form.cleaned_data['sorting']
        transmission = form.cleaned_data['transmissions']
        fuel = form.cleaned_data['fuels']
        ad_type = form.cleaned_data['ad_types']
        schedule = form.cleaned_data['schedules']
        level = form.cleaned_data['levels']
        price_min = form.cleaned_data['price_min']
        price_max = form.cleaned_data['price_max']
        subcategory = SubCategory.objects.filter(slug=category, is_active=True).only(
            'filter_transmissions', 'filter_fuels', 'filter_ad_types', 'filter_price_min', 'filter_price_max',
            'filter_schedules', 'filter_levels', 'filter_condition',
        ).first()
        category_f = Category.objects.filter(slug=category, is_active=True).only(
            'filter_transmissions', 'filter_fuels', 'filter_ad_types', 'filter_price_min', 'filter_price_max',
            'filter_schedules', 'filter_levels', 'filter_condition',
        ).first()
        if is_valid_queryparam(keyword_q):
            objects_list = objects_list.filter(
                Q(title__icontains=keyword_q) | Q(description__icontains=keyword_q)
            )
        if is_valid_queryparam(city):
            objects_list = objects_list.filter(
                Q(city__exact=city)
            )
        if is_valid_queryparam(sorting):
            objects_list = objects_list.order_by(
                sorting
            )
        if is_valid_queryparam(category):
            objects_list = objects_list.filter(
                Q(subcategory__slug__exact=category) | Q(category__slug__exact=category)
            )
        if subcategory and subcategory.filter_transmissions or category_f and category_f.filter_transmissions:
            if is_valid_queryparam(transmission):
                objects_list = objects_list.filter(
                    Q(standard__auto__transmission__exact=transmission) | Q(
                        standard__moto__transmission__exact=transmission)
                )
        if subcategory and subcategory.filter_fuels or category_f and category_f.filter_fuels:
            if is_valid_queryparam(fuel):
                objects_list = objects_list.filter(
                    Q(standard__auto__fuel__exact=fuel) | Q(standard__moto__fuel__exact=fuel)
                )
        if subcategory and subcategory.filter_ad_types or category_f and category_f.filter_ad_types:
            if is_valid_queryparam(ad_type):
                objects_list = objects_list.filter(
                    Q(standard__auto__ad_type__exact=ad_type) | Q(standard__moto__ad_type__exact=ad_type) |
                    Q(properties__ad_type__exact=ad_type) | Q(properties__house__ad_type__exact=ad_type)
                )
        if subcategory and subcategory.filter_price_min or category_f and category_f.filter_price_min:
            if is_valid_queryparam(price_min):
                objects_list = objects_list.filter(
                    price__gte=price_min
                )
        if subcategory and subcategory.filter_price_max or category_f and category_f.filter_price_max:
            if is_valid_queryparam(price_max):
                objects_list = objects_list.filter(
                    price__lte=price_max
                )
        if subcategory and subcategory.filter_schedules or category_f and category_f.filter_schedules:
            if is_valid_queryparam(schedule):
                objects_list = objects_list.filter(
                    Q(jobs__schedule__exact=schedule)
                )
        if subcategory and subcategory.filter_levels or category_f and category_f.filter_levels:
            if is_valid_queryparam(level):
                objects_list = objects_list.filter(
                    Q(jobs__level__exact=level)
                )
        if subcategory and subcategory.filter_condition or category_f and category_f.filter_condition:
            if is_valid_queryparam(condition):
                objects_list = objects_list.filter(
                    Q(standard__condition__exact=condition) | Q(standard__auto__condition__exact=condition)
                    | Q(standard__moto__condition__exact=condition)
                )
    paginator = Paginator(objects_list, 10)  # Show 1 contacts per page.
    page_number = request.GET.get('page')
    announcement = paginator.get_page(page_number)
    return render(request, 'ads/list.html', {
        'announcements': announcement, 'form': form,
        'subcategory': subcategory, "category_f": category_f
    })


def categories_and_sub(request, category_slug=None, sabcategory_slug=None):
    category = None
    subcategory = None
    objects_list = Announcement.ad_manager.active_ad()
    form = SearchForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug, is_active=True)
        objects_list = objects_list.filter(category=category.id)
        form.initial = {'categories': category.slug}
    if category_slug and sabcategory_slug:
        subcategory = get_object_or_404(
            SubCategory, category__slug=category_slug, slug=sabcategory_slug, is_active=True
        )
        objects_list = objects_list.filter(subcategory=subcategory.id)
        form.initial = {'categories': subcategory.slug}
    paginator = Paginator(objects_list, 1)  # Show 1 contacts per page.
    page_number = request.GET.get('page')
    announcement = paginator.get_page(page_number)
    return render(request, 'categories/ann_by_cat_and_sub.html', {'category': category, 'subcategory': subcategory,
                                                                  'announcements': announcement, 'form': form})


def announcement_detail(request, slug):
    announcement = get_object_or_404(Announcement.ad_manager.active_ad(), slug=slug)  # is_active=True
    form = MessageForm()
    cookie_name = f'visited-{announcement.slug}'
    # Using cookie
    if not request.COOKIES.get(f'visited-{announcement.slug}'):
        request.COOKIES[f'visited-{announcement.slug}'] = True

        # Using session
        # if not request.session.get(f'visited-{announcement.id}'):
        #     request.session[f'visited-{announcement.id}'] = True

        announcement.visits += 1
        announcement.save()
    context = {
        'announcement': announcement,
        'form': form,
    }

    response = render(request, 'ads/detail.html', context)
    response.set_cookie(cookie_name, True, max_age=24 * 60 * 60)
    return response


@login_required
@profile_complete_required
def add_announcement(request, category_id, subcat_id, form_class, section):
    category = get_object_or_404(Category, id=category_id, is_active=True)
    sub_category = get_object_or_404(SubCategory, id=subcat_id, is_active=True)

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            add_form = form.save(commit=False)
            add_form.category = category
            add_form.subcategory = sub_category
            add_form.profile = request.user.user_profile_related
            add_form.ip = request.META.get('REMOTE_ADDR')
            add_form.save()
            messages.add_message(request, messages.SUCCESS, 'Your ad will be published in a few minutes.',
                                 extra_tags="success")
            return redirect('ads:add_image_announcement', add_form.id)
        else:
            messages.add_message(request, messages.ERROR, 'Please fill in all fields correctly and try again.',
                                 extra_tags="danger")
    else:
        form = form_class()

    context = {
        'form': form,
        'category': category,
        'sub_category': sub_category,
        'section': section,
    }

    return render(request, 'ads/add_ad.html', context)


@login_required
@profile_complete_required
def add_standard_announcement(request, category_id, subcat_id):
    return add_announcement(request, category_id, subcat_id, StandardAdsForm, "add_standard")


@login_required
@profile_complete_required
def update_announcement(request, model_name, ann_id, form_class, section):
    announcement = get_object_or_404(model_name, id=ann_id, profile__user=request.user)
    if request.method == 'POST':
        form = form_class(request.POST, instance=announcement)
        if form.is_valid():
            add_form = form.save(commit=False)
            add_form.profile = request.user.user_profile_related
            add_form.ip = request.META.get('REMOTE_ADDR')
            add_form.save()
            messages.add_message(request, messages.SUCCESS, 'Your ad will be updated in a few minutes.',
                                 extra_tags="success")
            return redirect('accounts:user_ads')
        else:
            messages.add_message(request, messages.ERROR, 'Please fill in all fields correctly and try again.',
                                 extra_tags="danger")
    else:

templates/ads/add_ad.html
{% include 'ads/partial/add.html' with title='Place your ad in minutes' paragraf='Sell online what you no longer use and start earning' button_submit='Save and continue' %}

templates/ads/add_image.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="card card-background">
                <!-- card header  -->
                <div class="card-header card-background bg-white py-4">
                    <h4 class="mb-0">Add Images to {{ announcement.title }}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-4">
                            <form action="{% url 'ads:add_image_announcement' announcement.id %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Upload</button>
                                <a href="{% url 'accounts:update_profile' %}" class="btn btn-orange text-white">
                                    Finish
                                </a>
                            </form>
                        </div>
                        <div class="col-8">
                            <div class="row">
                                {% for image in announcement.announcement_images.all %}
                                    <div class="col-3">
                                        {% if image.image %}
                                            <figure class="figure">
                                                <img src="{{ image.image.url }}" class="rounded mb-2" alt="..."
                                                     width="150" height="150">
                                                <figcaption class="figure-caption text-center text-white">
                                                    {% if image.is_active %}Published{% else %}Unpublished{% endif %}
                                                </figcaption>
                                            </figure>
                                        {% endif %}
                                        <div class="d-flex flex-row bd-highlight mb-3 justify-content-center">
                                            <div class="me-2">
                                                <a href="{% url 'ads:modify_image_announcement' image.id %}"
                                                   class="btn btn-warning btn-sm">
                                                    Modify
                                                </a>
                                            </div>
                                            <div>
                                                <!-- Button trigger modal -->
                                                <button type="button" class="btn btn-primary btn-sm"
                                                        data-bs-toggle="modal"
                                                        data-bs-target="#exampleModal-{{ image.id }}">
                                                    Delete
                                                </button>
                                                <!-- Modal -->
                                                <div class="modal fade" id="exampleModal-{{ image.id }}" tabindex="-1"
                                                     aria-labelledby="exampleModalLabel-{{ image.id }}"
                                                     aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content card-background">
                                                            <div class="modal-header border-color-cs">
                                                                <h1 class="modal-title fs-5"
                                                                    id="exampleModalLabel-{{ image.id }}">
                                                                    Are you sure you want to delete this image?
                                                                </h1>
                                                                <button type="button" class="btn-close"
                                                                        data-bs-dismiss="modal"
                                                                        aria-label="Close"></button>
                                                            </div>
                                                            <div class="modal-body">
                                                                A deleted object cannot be recovered.
                                                            </div>
                                                            <div class="modal-footer border-color-cs">
                                                                <button type="button" class="btn btn-secondary"
                                                                        data-bs-dismiss="modal">Close
                                                                </button>
                                                                <form method="post"
                                                                      action="{% url 'ads:delete_image_announcement' image.id %}">
                                                                    {% csrf_token %}
                                                                    <button type="submit" class="btn btn-primary">
                                                                        Yes
                                                                    </button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ads/list.html
{% extends 'base.html' %}
{% load static %}
{% load query_helpers %}
{% load detects_mobile %}
{% block javascript %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/wishlist.js' %}"></script>
    <script src="{% static 'js/reset_filters.js' %}"></script>
{% endblock %}
{% block content %}
    <section class="obj-list">
        <div class="row">
            {% include 'ads/partial/filters/search_form.html' %}
            {% if not request|is_mobile %}
                <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-3 d-none d-sm-none d-md-block">
                    {% if subcategory.filter_condition or category_f.filter_condition %}
                        {% include 'ads/partial/filters/conditions.html' %}
                    {% endif %}
                    {% if subcategory.filter_ad_types or category_f.filter_ad_types %}
                        {% include 'ads/partial/filters/ad_types.html' %}
                    {% endif %}
                    {% if subcategory.filter_fuels or category_f.filter_fuels %}
                        {% include 'ads/partial/filters/fuels.html' %}
                    {% endif %}
                    {% if subcategory.filter_transmissions or category_f.filter_transmissions %}
                        {% include 'ads/partial/filters/transmissions.html' %}
                    {% endif %}
                    {% if subcategory.filter_price_min and subcategory.filter_price_max or category_f.filter_price_min and category_f.filter_price_max %}
                        {% include 'ads/partial/filters/price_filter.html' %}
                    {% endif %}
                    {% if subcategory.filter_schedules or category_f.filter_schedules %}
                        {% include 'ads/partial/filters/schedules.html' %}
                    {% endif %}
                    {% if subcategory.filter_levels or category_f.filter_levels %}
                        {% include 'ads/partial/filters/levels.html' %}
                    {% endif %}
                </div>
            {% endif %}
            <div class="col-xxl-10 col-xl-10 col-lg-10 col-md-9 col-sm-12 col-12">
                <div class="d-flex flex-row mb-3 align-items-center">
                    {% if request|is_mobile %}
                        <div class="p-1 d-block d-sm-block d-md-none">
                            {% include 'ads/partial/filters/mobile_filter.html' %}
                        </div>
                    {% endif %}
                    <div class="p-1 text-white">
                        <i class="bi bi-arrow-down-up"></i> Sort By:
                    </div>
                    <div class="p-1">
                        {% include 'ads/partial/filters/sorting.html' %}
                    </div>
                    <div class="p-1 ms-auto text-white">
                        {{ announcements|length }} offers
                    </div>
                </div>
                {% for ads in announcements %}
                    {% include 'ads/partial/card.html' %}
                {% empty %}
                    {% include 'partial/no_result_found.html' %}
                {% endfor %}
                {% include 'partial/pagination.html' with page_obj=announcements %}
            </div>
        </div>
    </section>
{% endblock %}

templates/ads/modify_image.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="card card-background">
                <!-- card header  -->
                <div class="card-header bg-white py-4 card-background">
                    <h4 class="mb-0">Update Image</h4>
                </div>
                <div class="card-body">
                    {% if image.image %}
                        <figure class="figure">
                            <img src="{{ image.image.url }}" class="rounded mb-3" alt="..." width="200" height="150">
                            <figcaption class="figure-caption">
                                Actual Image
                            </figcaption>
                        </figure>
                    {% endif %}
                    <form action="{% url 'ads:modify_image_announcement' image.id %}" method="post"
                          enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/ads/update_ad.html
{% include 'ads/partial/add.html' with title='Update your ad in minutes' paragraf='Sell online what you no longer use and start earning' button_submit='Update' %}